version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: graphiti-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/graphiti123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - ./config/neo4j.conf:/conf/neo4j.conf:ro
    networks:
      - memory-network

  graphiti:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphiti-server
    ports:
      - "5700:5700"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=graphiti123
      - MEMORY_TTL_DAYS=30
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    depends_on:
      - neo4j
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - memory-network

  redis:
    image: redis:7-alpine
    container_name: graphiti-redis
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data
    networks:
      - memory-network

networks:
  memory-network:
    driver: bridge

volumes:
  neo4j-data:
  neo4j-logs:
  redis-data: