services:
  # Main MCP Server
  - type: web
    name: pulser-mcp-simple
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: /mnt/data/mcp.db
      - key: LOG_LEVEL
        value: info
    autoDeploy: true
    branch: claude-mcp-simple
    region: oregon
    healthCheckPath: /health
    disk:
      name: mcp-storage
      mountPath: /mnt/data
      sizeGB: 1