# Render Blueprint for Pulser MCP Services
# Deploy all services with one click

services:
  # Remote MCP Bridge (SSE endpoint)
  - type: web
    name: pulser-mcp-bridge
    env: node
    region: oregon
    plan: standard
    buildCommand: cd remote-mcp && npm install
    startCommand: node remote-mcp/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PULSER_URL
        value: https://pulser-mcp-services.onrender.com
      - key: PULSER_JWT_SECRET
        generateValue: true
      - key: REDIS_PASSWORD
        value: Postgres_26!
      - key: MCP_ADMIN_PASS
        value: Postgres_admin
    healthCheckPath: /health
    
  # Main MCP Services (Scout, Creative, Financial, etc.)
  - type: web
    name: pulser-mcp-services
    env: docker
    region: oregon
    plan: standard
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: REDIS_PASSWORD
        value: Postgres_26!
      - key: NEO4J_PASSWORD
        value: Postgres_26!
      - key: MCP_ADMIN_PASS
        value: Postgres_admin
      - key: PULSER_JWT_SECRET
        sync: false
    healthCheckPath: /health
    
  # Redis Cache
  - type: redis
    name: pulser-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru
    
  # PostgreSQL (instead of Neo4j for Render)
  - type: postgres
    name: pulser-postgres
    region: oregon
    plan: starter
    databaseName: pulser_mcp
    user: pulser_admin
    
# Static site for documentation
staticSites:
  - type: web
    name: pulser-mcp-docs
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./docs
    routes:
      - type: rewrite
        source: /*
        destination: /index.html