version: '3.8'

services:
  mindsdb:
    image: mindsdb/mindsdb:latest
    container_name: unified-mindsdb
    ports:
      - "47334:47334"  # MindsDB API
      - "47335:47335"  # MindsDB MySQL API  
      - "47336:47336"  # MindsDB MongoDB API
      - "8891:8891"    # MindsDB Studio
    environment:
      - MINDSDB_STORAGE_DIR=/mindsdb_storage
      - MINDSDB_CONFIG_PATH=/config/mindsdb.conf
    volumes:
      - mindsdb-data:/mindsdb_storage
      - ./config/mindsdb.conf:/config/mindsdb.conf:ro
      - ./data:/data
    networks:
      - unified-network

  postgres:
    image: postgres:15-alpine
    container_name: unified-postgres
    environment:
      - POSTGRES_USER=mindsdb
      - POSTGRES_PASSWORD=mindsdb123
      - POSTGRES_DB=unified_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - unified-network

  redis:
    image: redis:7-alpine
    container_name: unified-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - unified-network

networks:
  unified-network:
    driver: bridge

volumes:
  mindsdb-data:
  postgres-data:
  redis-data: