name: percy
codename: percy
version: 1.0.0
type: visual_qa
description: >
  Visual regression testing agent using Percy. Captures snapshots of rendered pages
  and compares against approved baselines to detect UI regressions.
permissions:
  - fs:project-readonly      # can read the built site
  - network:access           # can fetch preview URLs
  - ci:report                # can annotate CI with pass/fail
triggers:
  - "CI job:percy-snap"
  - "Manual:percysnap"
outputs:
  - report_url
  - status
memory_tags:
  - visual-qa
  - percy
